### ISSUE TITLE
Images of other items appear on top of expanded locker menu

### ISSUE THREAD

**Issue by AlanCoding** [ShareLocker/ShareLockers#56]
I'm trying to attach an image to show this. The images of items in neighbor boxes appear on top of the expanded locker, obstructing any operations on a locker.

In the image, the pluto item is in B1, but the menu for A1 is expanded here.

![screenshot 2015-07-19 12 19 18](https://cloud.githubusercontent.com/assets/1385596/8766707/8496e584-2e10-11e5-8f61-87ca1aefb1c4.png)

**Comment by wholetthedogsout** [comment]
closed
