### ISSUE TITLE
Naive datetime warning

### ISSUE THREAD

**Issue by AlanCoding** [ShareLocker/ShareLockers#58]
When starting the shell (manage.py shell), the following warning is thrown:

SQLite received a naive datetime (2015-07-19 16:37:38.731854) while time zone support is active.

If I remember correctly, I have been using the Django timezone objects. My preferred resolution would be to find all instances of naive datetime and changing those to proper timezone use.

**Comment by jwaldrep** [comment]
Pull Request #61 removed naive datetimes from the code. As of 7/20/15, these warnings do not show up on the heroku shell (with recently-replaced db/migrations), but do show still up on local SQLite version, even with a fresh database.
