### ISSUE TITLE
User item list boxes are very narrow

### ISSUE THREAD

**Issue by AlanCoding** [ShareLocker/ShareLockers#59]
This is a css styling issue to the best of my knowledge. The image below shows the behavior. Even there is plenty of horizontal space, the title "Wedding fake candle" puts the 3 words on separate lines.

![screenshot 2015-07-19 12 58 22](https://cloud.githubusercontent.com/assets/1385596/8766849/051996b6-2e16-11e5-87c3-a11450306b4c.png)

**Comment by falont23** [comment]
This is a quick fix, I already have a class for it called .info-card. I will push that and the logo tonight.
